apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp
  labels:
    app: myapp
spec:
  rules:
  - host: stage-myapp.dev1.pcfgcp.pkhamdee.com
    http:
      paths:
      - backend:
          serviceName: myapp
          servicePort: 80
